const { cmd } = require('../command');
const axios = require('axios');

// Main AI Command using Pollinations API
cmd({
    pattern: "ai",
    alias: ["bot", "ask", "gpt", "gpt4", "chat", "ask2"],
    desc: "Chat with AI assistant By Muzamil",
    category: "ai",
    react: "🤖",
    filename: __filename,
    use: ".ai <question>"
},
async (conn, mek, m, { from, args, q, reply, react }) => {
    try {
        if (!q) return reply("❌ *Please provide a message!*\n\n*Example:* `.ai What is JavaScript?`");

        await react("⏳");
        
        // Using Pollinations AI API (only this API)
        const apiUrl = `https://text.pollinations.ai/${encodeURIComponent(q)}`;
        const { data } = await axios.get(apiUrl, { timeout: 30000 });

        // Handle response (Pollinations returns plain text)
        let response = data;
        
        if (!response || response.length < 1) {
            await react("❌");
            return reply("🤖 *AI Error:* Failed to get response. Please try again later.");
        }

        await reply(`🤖 *AI Assistant*\n\n${response}\n\n⚡ *BY: MUZAMIL*`);
        await react("✅");
        
    } catch (e) {
        console.error("AI Error:", e);
        await react("❌");
        reply(`❌ *Error:* ${e.message || "Network issue! Try again."}`);
    }
});

// OpenAI Command using Pollinations
cmd({
    pattern: "openai",
    alias: ["chatgpt", "gpt3", "opengpt", "gpt"],
    desc: "Chat with OpenAI (via Pollinations)",
    category: "ai",
    react: "🧠",
    filename: __filename,
    use: ".openai <question>"
},
async (conn, mek, m, { from, args, q, reply, react }) => {
    try {
        if (!q) return reply("❌ *Please provide a message!*\n\n*Example:* `.openai Write a poem`");

        await react("⏳");
        
        // Pollinations API with openai model
        const apiUrl = `https://text.pollinations.ai/${encodeURIComponent(q)}?model=openai`;
        const { data } = await axios.get(apiUrl, { timeout: 30000 });

        if (!data) {
            await react("❌");
            return reply("🧠 *OpenAI Error:* No response received. Try again!");
        }

        await reply(`🧠 *OpenAI Response*\n\n${data}\n\n✨ *Generated by Muzamil*`);
        await react("✅");
        
    } catch (e) {
        console.error("OpenAI Error:", e);
        await react("❌");
        reply(`❌ *Error:* ${e.message || "API might be down!"}`);
    }
});

// DeepSeek AI Command using Pollinations
cmd({
    pattern: "deepseek",
    alias: ["deep", "seek", "deepai", "ds"],
    desc: "Chat with DeepSeek AI (via Pollinations)",
    category: "ai",
    react: "🔍",
    filename: __filename,
    use: ".deepseek <question>"
},
async (conn, mek, m, { from, args, q, reply, react }) => {
    try {
        if (!q) return reply("❌ *Please provide a message!*\n\n*Example:* `.deepseek Explain quantum physics`");

        await react("⏳");
        
        // Pollinations API with deepseek model
        const apiUrl = `https://text.pollinations.ai/${encodeURIComponent(q)}?model=deepseek`;
        const { data } = await axios.get(apiUrl, { timeout: 30000 });

        if (!data) {
            await react("❌");
            return reply("🔍 *DeepSeek Error:* Failed to get response. Try again!");
        }

        await reply(`🔍 *DeepSeek AI Response*\n\n${data}\n\n📚 *Powered by Muzamil*`);
        await react("✅");
        
    } catch (e) {
        console.error("DeepSeek Error:", e);
        await react("❌");
        reply(`❌ *Error:* ${e.message || "API issue! Please retry."}`);
    }
});

// Bing AI Command using Pollinations
cmd({
    pattern: "bing",
    alias: ["copilot", "bingai"],
    desc: "Chat with Microsoft Bing AI (via Pollinations)",
    category: "ai",
    react: "🌊",
    filename: __filename,
    use: ".bing <question>"
},
async (conn, mek, m, { from, args, q, reply, react }) => {
    try {
        if (!q) return reply("❌ *Please provide a message!*\n\n*Example:* `.bing Latest news`");

        await react("⏳");
        
        // Pollinations API with bing model (searchgpt)
        const apiUrl = `https://text.pollinations.ai/${encodeURIComponent(q)}?model=searchgpt`;
        const { data } = await axios.get(apiUrl, { timeout: 30000 });

        if (!data) {
            await react("❌");
            return reply("🌊 *Bing AI Error:* No response. Try later!");
        }

        await reply(`🌊 *Bing AI Response*\n\n${data}\n\n🔗 *Powered by Muzamil*`);
        await react("✅");
        
    } catch (e) {
        console.error("Bing Error:", e);
        await react("❌");
        reply(`❌ *Error:* ${e.message}`);
    }
});