const { cmd } = require("../command");
const axios = require("axios");
const fs = require("fs");

cmd({
  pattern: "createimg",
  alias: ["nanobanana", "imagine", "searchimg", "pinterest"],
  react: "🖼️",
  desc: "Search real images from Pinterest",
  category: "main",
  filename: __filename,
  use: ".createimg <search query>"
}, async (conn, mek, m, { q, from, reply }) => {
  try {
    if (!q) return reply("❌ *Please provide a search query!*\n\n*Example:* .createimg Nature");

    await reply(`🔍 *Creating images for:* ${q}\n⏳ Please wait...`);

    // Pinterest API (search - not generate)
    const apiUrl = `https://allstars-apis.vercel.app/pinterest?search=${encodeURIComponent(q)}`;
    
    const response = await axios.get(apiUrl);
    
    if (!response.data || !response.data.data || response.data.data.length === 0) {
      return reply(`❌ *No images found for:* ${q}\n\nTry different keywords!`);
    }

    // Get first 5-10 images (limit to avoid spam)
    const images = response.data.data.slice(0, 8);
    const totalCount = response.data.count || images.length;
    
    // Send first image with caption
    const firstImage = images[0];
    const imageBuffer = await axios.get(firstImage, { responseType: "arraybuffer" });
    
    let caption = `*🖼️ IMAGE CREATED*\n\n`;
    caption += `🔍 *Query:* ${q}\n`;
    caption += `📸 *Found:* ${totalCount} images\n`;
    caption += `🖼️ *Showing:* ${images.length} images\n\n`;
    caption += `> Ƥσωɛяɛ∂ βʏ: Μʋʓαмιℓ 🚀`;
    
    await conn.sendMessage(from, {
      image: Buffer.from(imageBuffer.data, "binary"),
      caption: caption
    });
    
    // Send remaining images as separate messages
    for (let i = 1; i < images.length; i++) {
      try {
        const imgBuffer = await axios.get(images[i], { responseType: "arraybuffer" });
        await conn.sendMessage(from, {
          image: Buffer.from(imgBuffer.data, "binary"),
          caption: `🖼️ *Image ${i + 1} of ${images.length}*\n🔍 *Query:* ${q}`
        });
        
        // Small delay to avoid rate limiting
        await new Promise(resolve => setTimeout(resolve, 500));
        
      } catch (err) {
        console.error(`Error sending image ${i + 1}:`, err);
        // Continue with next image
      }
    }
    
    await conn.sendMessage(from, {
      text: `✅ *Done!* Found and sent ${images.length} images for "*${q}*"`,
      edit: m.key
    });
    
  } catch (error) {
    console.error("Pinterest Search Error:", error);
    reply(`❌ *Error:* ${error.message || "Something went wrong!"}\n\nTry again later.`);
  }
});

cmd({
  pattern: "stablediffusion",
  alias: ["sdiffusion", "imagine2"],
  react: "🚀",
  desc: "Generate an image using AI.",
  category: "main",
  filename: __filename
}, async (conn, mek, m, { q, reply }) => {
  try {
    if (!q) return reply("Please provide a prompt for the image.");

    await reply("> *CREATING IMAGINE ...🔥*");

    const apiUrl = `https://api.siputzx.my.id/api/ai/stable-diffusion?prompt=${encodeURIComponent(q)}`;

    const response = await axios.get(apiUrl, { responseType: "arraybuffer" });

    if (!response || !response.data) {
      return reply("Error: The API did not return a valid image. Try again later.");
    }

    const imageBuffer = Buffer.from(response.data, "binary");

    await conn.sendMessage(m.chat, {
      image: imageBuffer,
      caption: `💸 *Imagine Generated BY MUZAMIL-XD*🚀\n✨ Prompt: *${q}*`
    });

  } catch (error) {
    console.error("FluxAI Error:", error);
    reply(`An error occurred: ${error.response?.data?.message || error.message || "Unknown error"}`);
  }
});

cmd({
  pattern: "stabilityai",
  alias: ["stability", "imagine3"],
  react: "🚀",
  desc: "Generate an image using AI.",
  category: "main",
  filename: __filename
}, async (conn, mek, m, { q, reply }) => {
  try {
    if (!q) return reply("Please provide a prompt for the image.");

    await reply("> *CREATING IMAGINE ...🔥*");

    const apiUrl = `https://api.siputzx.my.id/api/ai/stabilityai?prompt=${encodeURIComponent(q)}`;

    const response = await axios.get(apiUrl, { responseType: "arraybuffer" });

    if (!response || !response.data) {
      return reply("Error: The API did not return a valid image. Try again later.");
    }

    const imageBuffer = Buffer.from(response.data, "binary");

    await conn.sendMessage(m.chat, {
      image: imageBuffer,
      caption: `💸 *Imagine Generated BY MUZAMIL-XD*🚀\n✨ Prompt: *${q}*`
    });

  } catch (error) {
    console.error("FluxAI Error:", error);
    reply(`An error occurred: ${error.response?.data?.message || error.message || "Unknown error"}`);
  }
});
